### PR TITLE
Some optimizations

### PR DESCRIPTION
**Pull request by thegrb93**

### CODE REVIEW

**Comment by thegrb93** [comment]
Looks like im on the wrong branch.

**Comment by zocat64** [comment]
the develop branch is the right one. trying to get the hud working before pushing to master

**Comment by redpr1sm** [comment]
gave you collaborator status, by the way.

**Comment by thegrb93** [comment]
I used the master version by accident.

**Comment by zocat64** [comment]
ah. gotcha.

**Pull request closed without merging**
